import type { RecipeSummary } from '@/types/recipe';

export const MOCK_RECIPES: RecipeSummary[] = [
  {
    id: 'mock-1',
    name: '소불고기 도시락',
    thumbnail_url: null,
    concept_tags: ['taste', 'volume'],
    dish_type: 'rice',
    difficulty: 'medium',
    calories: 520,
    cooking_time_minutes: 30,
    price_tier: 2,
    price_confidence: 0.8,
    youtube_video_id: null,
  },
  {
    id: 'mock-2',
    name: '계란말이',
    thumbnail_url: null,
    concept_tags: ['easy', 'budget'],
    dish_type: 'side',
    difficulty: 'easy',
    calories: 180,
    cooking_time_minutes: 10,
    price_tier: 1,
    price_confidence: 0.9,
    youtube_video_id: 'dQw4w9WgXcQ',
  },
  {
    id: 'mock-3',
    name: '닭가슴살 샐러드',
    thumbnail_url: null,
    concept_tags: ['nutrition', 'easy'],
    dish_type: 'one_plate',
    difficulty: 'easy',
    calories: 320,
    cooking_time_minutes: 15,
    price_tier: 2,
    price_confidence: 0.7,
    youtube_video_id: null,
  },
  {
    id: 'mock-4',
    name: '김치볶음밥',
    thumbnail_url: null,
    concept_tags: ['budget', 'easy'],
    dish_type: 'rice',
    difficulty: 'easy',
    calories: 450,
    cooking_time_minutes: 15,
    price_tier: 1,
    price_confidence: 0.85,
    youtube_video_id: 'dQw4w9WgXcQ',
  },
  {
    id: 'mock-5',
    name: '제육볶음',
    thumbnail_url: null,
    concept_tags: ['taste', 'volume'],
    dish_type: 'rice',
    difficulty: 'medium',
    calories: 580,
    cooking_time_minutes: 25,
    price_tier: 2,
    price_confidence: 0.75,
    youtube_video_id: null,
  },
  {
    id: 'mock-6',
    name: '오므라이스',
    thumbnail_url: null,
    concept_tags: ['taste', 'easy'],
    dish_type: 'one_plate',
    difficulty: 'easy',
    calories: 480,
    cooking_time_minutes: 20,
    price_tier: 1,
    price_confidence: 0.8,
    youtube_video_id: 'dQw4w9WgXcQ',
  },
  {
    id: 'mock-7',
    name: '두부조림',
    thumbnail_url: null,
    concept_tags: ['budget', 'nutrition'],
    dish_type: 'side',
    difficulty: 'easy',
    calories: 200,
    cooking_time_minutes: 20,
    price_tier: 1,
    price_confidence: 0.9,
    youtube_video_id: null,
  },
  {
    id: 'mock-8',
    name: '잡채',
    thumbnail_url: null,
    concept_tags: ['taste', 'volume'],
    dish_type: 'side',
    difficulty: 'medium',
    calories: 350,
    cooking_time_minutes: 40,
    price_tier: 2,
    price_confidence: 0.6,
    youtube_video_id: null,
  },
  {
    id: 'mock-9',
    name: '참치마요 주먹밥',
    thumbnail_url: null,
    concept_tags: ['easy', 'budget'],
    dish_type: 'rice',
    difficulty: 'easy',
    calories: 400,
    cooking_time_minutes: 10,
    price_tier: 1,
    price_confidence: 0.85,
    youtube_video_id: null,
  },
  {
    id: 'mock-10',
    name: '미역국',
    thumbnail_url: null,
    concept_tags: ['nutrition', 'budget'],
    dish_type: 'soup',
    difficulty: 'easy',
    calories: 150,
    cooking_time_minutes: 30,
    price_tier: 1,
    price_confidence: 0.7,
    youtube_video_id: null,
  },
];
